spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.78.229.24:3306/zrzk?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jmx:
    enabled: false
server:
  port: 8001

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #开启sql日志
    map-underscore-to-camel-case: false                     #关闭驼峰自动转下划线

logging:
  config: classpath:log/logback-spring.xml    #日志的配置文件
  #path: D:\idea\IdeaProjects\zrzk_parent\zrzk_rms\src\main\resources  #日志输出的路径
